# # coding: utf-8
# import yaml

# # from cfg.paths import CFG_SELECTED_SKUS

# F_CATEGORY_FORECAST = 'CATEGORY_FORECAST'
# F_CONNECT = 'CONNECT'
# F_DATA = 'DATA'
# F_DATABASE = 'DATABASE'
# F_DI_TRADEFLOW = 'DI_TRADEFLOW'
# F_EIB_OSA = 'EIB_OSA'
# F_EIB_PRICE = 'EIB_PRICE'
# # F_FILENAME = 'FILENAME'
# F_FILES = 'FILES'
# F_FILEPATH = 'FILEPATH'
# F_IL_OFFTAKE = 'IL_OFFTAKE'
# F_IL_OFFTAKE_CHANNEL = 'IL_OFFTAKE_CHANNEL'
# F_IL_SELLIN = 'IL_SELLIN'
# F_INDEX = 'INDEX'
# F_OSA_EIB = 'F_OSA_EIB'
# F_SCHEMA = 'SCHEMA'
# F_SMARTPATH = 'SMARTPATH'
# F_TABLE_NAME = 'TABLE NAME'
# F_TABLES = 'TABLES'
# F_VERSION = 'VERSION'
# F_MAPPING_SKU_STD_INFO = 'MAPPING_SKU_STD_INFO'
# F_MAPPING_OSA_EIB = 'MAPPING_OSA_EIB'
# F_IL_MAP_SELLIN_EIB = 'il_mapping_sellin_eib'
# F_IL_OG = 'IL_OG'
# F_IL_UPLIFT = 'IL_UPLIFT'

# # DC files
# F_DC_POS_PRODUCT_LIST = 'DC_PRODUCT_LIST'
# F_DC_POS = 'DC_POS'
# F_DC_OSA = 'DC_OSA'
# F_DC_ANP = 'DC_ANP'
# F_DC_SELLIN = 'DC_SELLIN'
# F_DC_SELLIN_HIST = 'DC_SELLIN_HIST'
# F_DC_SPINV = 'DC_SPINV'
# F_DC_SELLOUT = 'DC_SELLOUT'
# F_DC_STORE_DISTRIB = 'DC_STORE_DISTRIB'
# F_DC_CUSTOMER = 'DC_CUSTOMER'

# with open(CFG_SELECTED_SKUS, 'r') as ymlf:
#     selected_skus = yaml.load(ymlf)

# SELECTED_SKUS_DC = selected_skus['DC']
# SELECTED_SKUS_IL = selected_skus['IL']
